### PR TITLE
Add gpt-4o-mini for both web and api access

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Reference:
- https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
> 切换到 chatgpt web gpt-4o mini 报错： 错误:
> 
> Buffer is not defined

I can't reproduce it 😅 

image

**Comment by josStorer** [comment]
Use the complete 1.87MB chromium.zip @anuxs

**Comment by josStorer** [comment]
@PeterDaveHello I think it should be ready for release today; I'm adding support for unlimited custom APIs, and plan to release it together.

**Comment by PeterDaveHello** [comment]
@josStorer just asking, do you think the unlimited custom APIs feature will also handle the new API on OpenAI.com, just before we manually add or update a model in this project, this feature could be very useful!

**Comment by josStorer** [comment]
@PeterDaveHello A new version has just been released. Yes, it supports custom APIs for both the OpenAI web mode and API mode. Not only that, it actually supports custom model names for all modes, including Azure deployment names, etc.

image

**Pull request merged**
