### PR TITLE
Make all the "Selection Tools" functions optional and configurable

### PR DESCRIPTION
**Pull request by PeterDaveHello**
🎉

### CODE REVIEW

**Comment by josStorer** [comment]
This part was actually deliberately removed because it is now possible to customize selection tools, and too many translation tools seem a bit messy.

**Comment by PeterDaveHello** [comment]
> This part was actually deliberately removed because it is now possible to customize selection tools, and too many translation tools seem a bit messy.

That's exactly the reason why I want them to be optional :laughing:

**Comment by josStorer** [comment]
I lean towards only keeping some particularly necessary tools as presets, such as translating any language into the user's language, and translating any language into the internationally common English. For other needs, users can customize directly, and there is no need to add more built-in presets.

**Comment by PeterDaveHello** [comment]
So this patch will make both the "Translate (To Chinese)" & "Translate (Bidirectional)" functions not directly enabled, so it should be good with the idea? Or do you mean you'd entirely redesign this part of the feature? Thanks.

**Comment by PeterDaveHello** [comment]
My current point is that there are two options that can't be turned off which may cause me to click the wrong one or decrease the efficiency in selecting the right one :laughing: 

Screenshot:
image

**Comment by josStorer** [comment]
You can export all data and edit the activeSelectionTools field, clear out the old preset tools, and then re-import.

image

**Comment by PeterDaveHello** [comment]
Just to clarify, is this extra step only necessary for existing users? It seems like a fresh install wouldn't have this issue, right? If that's the case, then we can close this PR for sure! Thanks!

**Comment by josStorer** [comment]
@PeterDaveHello This step is only needed by a very small number of users, as only in specific versions were these two options set to be enabled, and in many versions since then they have been turned off by default. If you have never modified the activated tools, or have never activated these two tools, then upgrading to the new version will not encounter this problem.

**Comment by PeterDaveHello** [comment]
Got it, thanks again!

**Pull request closed without merging**
